name: Deploy to VPS

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to Digital Ocean
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/camcakes
            git fetch --all --tags
            git checkout tags/${{ github.event.release.tag_name }}
            npm install --production
            pm2 restart camcakes
